### PR TITLE
7 body image and text styling

### PR DESCRIPTION
**Pull request by drowley8**
This PR gives artwork to the 4-panel artboard section of the page. Each block has it's own unique id represented in the CSS file; This is the mechanic that gives each block its respective background image. Text is justified using flexbox.

Two CSS global variables were added to keep track of page theme colors.

Note: correct font WILL NOT WORK if it is not installed on the user's machine; advise choosing a new font that's link-able online such as those available on fonts.google.com.

Multi-resolution background images were uploaded, but not utilized.

Feature implementation was not timed.

Font sizes are currently set by pixel and are thus very rigid.

This PR solves issue #7

### CODE REVIEW

**Review by WesleyMcGhee — APPROVED** [review]
Seems to match the design file, code looks good.

**Review by normanjli — APPROVED** [review]
CSS looks excellent, well written and align with other CSS files in Repo.

**Review by MichaelJHTaggart — APPROVED** [review]
Great work and well thought out PR! 

Typically the correct font files WOFF/WOFF2 (Web Open Font Format versions 1 and 2) are provided for self-hosting OR as you suggested using an online service. More can be read here about both:

https://developer.mozilla.org/en-US/docs/Learn/CSS/Styling_text/Web_fonts

Here is a good article that explores why one would self-host:
https://medium.com/going-fullstack/self-hosting-web-font-files-6a46bfc36ffd

**Comment by drowley8** [comment]
And then there's the fact that we don't technically have the legal licensing to host the particular font we want to use (This font, by Monotype is available for licensing for web use at the annual cost of $39.99 per weight assuming the page using the font does not exceed 10,000 view per month). Fonts can get kinda pricey

**Pull request merged**
